-- phpMyAdmin SQL Dump
-- version 5.2.1
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1
-- Generation Time: Apr 05, 2026 at 06:51 AM
-- Server version: 10.4.32-MariaDB
-- PHP Version: 8.2.12

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `bd_crop`
--

-- --------------------------------------------------------

--
-- Table structure for table `crops`
--

CREATE TABLE `crops` (
  `crop name` varchar(100) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- --------------------------------------------------------

--
-- Table structure for table `district`
--

CREATE TABLE `district` (
  `District_name` varchar(100) NOT NULL,
  `description` varchar(1000) DEFAULT '',
  `imagePath` varchar(1000) DEFAULT ''
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

--
-- Dumping data for table `district`
--

INSERT INTO `district` (`District_name`, `description`, `imagePath`) VALUES
('Bagerhat', 'Bagerhat District (Bengali: বাগেরহাট জেলা) is a district in south-western Bangladesh. It is a part of Khulna Division.', 'https://upload.wikimedia.org/wikipedia/commons/4/4f/Sixty_Dome_Mosque%2CBagerhat.jpg;https://upload.wikimedia.org/wikipedia/commons/3/3c/Wildlife_Breeding_Center%2C_Karamjal%2C_Sundarban.jpg;'),
('Bandarban', 'Bandarban District (Bengali: বান্দরবান জেলা), officially Bandarban Hill District, is a district in South-Eastern Bangladesh, and a part of the Chittagong Division.[6] It is one of the three hill districts of Bangladesh and a part of the Chittagong Hill Tracts, the others being Rangamati District and Khagrachhari District. Bandarban district (4,479 km2) is not only the most remote district of the country, but also the least populous (population 388,000).[7] There is an army contingent at Bandarban Cantonment.', 'https://upload.wikimedia.org/wikipedia/commons/1/1c/Buddha_Dhatu_Jadi_06.jpg;https://upload.wikimedia.org/wikipedia/commons/9/94/Keokradong_10.jpg;https://upload.wikimedia.org/wikipedia/commons/7/76/Boga_Lake_%286843119656%29.jpg;https://upload.wikimedia.org/wikipedia/commons/b/be/Bandarban_District_upazila_geocode_map_-_Small_Area_Atlas_Bangladesh.svg'),
('Barguna', 'Barguna District (Bengali: বরগুনা জেলা; Bengali pronunciation: [borˈguna d͡ʒela]) is a district in Barisal Division, in southern Bangladesh.[6] Barguna subdivision was established in 1969 and promoted to a district on 28 February 1984.', 'https://upload.wikimedia.org/wikipedia/commons/b/b5/Seabirds_in_Barguna_Coastal_area%2C_Bangladesh_%283%29.jpg;https://upload.wikimedia.org/wikipedia/commons/c/c6/%E0%A6%AC%E0%A6%BF%E0%A6%AC%E0%A6%BF_%E0%A6%9A%E0%A6%BF%E0%A6%A8%E0%A6%BF_%E0%A6%90%E0%A6%A4%E0%A6%BF%E0%A6%B9%E0%A6%BE%E0%A6%B8%E0%A6%BF%E0%A6%95_%E0%A6%B6%E0%A6%BE%E0%A6%B9%E0%A7%80_%E0%A6%AE%E0%A6%B8%E0%A6%9C%E0%A6%BF%E0%A6%A6.jpg;https://upload.wikimedia.org/wikipedia/commons/c/c6/Burishwar_River_in_Barguna%2C_Bangladesh_%282%29.jpg;https://upload.wikimedia.org/wikipedia/commons/4/4d/Barguna_Coastal_area%2C_Bangladesh_%282%29.jpg'),
('Barishal', 'Barisal District, officially Barishal District[5] (Bengali: বরিশাল জেলা) is a district in south-central Bangladesh, it was formerly called Bakerganj district, and established in 1797.[6] Its headquarters is in Barisal city, which is also the headquarters of Barisal Division.', 'https://upload.wikimedia.org/wikipedia/commons/6/6f/Guthiya_mosque_Ri_palash_03.jpg;https://upload.wikimedia.org/wikipedia/commons/6/65/%E0%A6%A6%E0%A7%81%E0%A6%B0%E0%A7%8D%E0%A6%97%E0%A6%BE%E0%A6%B8%E0%A6%BE%E0%A6%97%E0%A6%B0.JPG;https://upload.wikimedia.org/wikipedia/commons/9/98/Oxford_Mission_Church%2C_Barishal.JPG'),
('Bhola', 'Bhola District (Bengali: ভোলা জেলা) is an administrative district of Barisal Division in south-central Bangladesh, which includes Bhola Island, the largest island of Bangladesh. It has an area of 3,403.48 km2.[3] It is bounded by Lakshmipur and Barisal District to the north, the Bay of Bengal to the south, by Lakshmipur and Noakhali districts, the (lower) Meghna river and Shahbazpur Channel to the east, and by Patuakhali District and the Tetulia river to the west.', 'https://upload.wikimedia.org/wikipedia/commons/5/5b/%E0%A6%AD%E0%A7%8B%E0%A6%B2%E0%A6%BE_%E0%A6%B9%E0%A6%BE%E0%A6%9C%E0%A6%BE%E0%A6%B0_%E0%A6%AC%E0%A6%9B%E0%A6%B0%E0%A7%87%E0%A6%B0_%E0%A6%AE%E0%A6%B8%E0%A6%9C%E0%A6%BF%E0%A6%A6.jpg;https://upload.wikimedia.org/wikipedia/commons/f/f8/Char_Kukri-Mukri_Wildlife_Sanctuary.jpg;https://upload.wikimedia.org/wikipedia/commons/a/a4/Bhola_District_upazila_geocode_map_-_Small_Area_Atlas_Bangladesh.svg'),
('Bogra', 'Bogra District, officially Bogura District[3] (Bengali: বগুড়া জেলা), is a district in the northern part of Bangladesh, in Rajshahi Division.[4] Bogra is an industrial city where many small and mid-sized companies are sited. Bogra was a part of the Pundravardhana territory of ancient Bengal and the ruins of its capital can be found in northern Bogra. Bogra is named after the independent sultan of Bengal Nasiruddin Bughra Khan (1287–1291).', 'https://upload.wikimedia.org/wikipedia/commons/9/91/Kherua_Mosque_Sherpur.jpg;https://upload.wikimedia.org/wikipedia/commons/8/8c/Mahasthangar_Gokul_Medh_Bogra_Bangladesh_%283%29.JPG;https://upload.wikimedia.org/wikipedia/commons/e/e1/Sannasir_Vita_%28Front%29.jpg;https://en.wikipedia.org/wiki/Bogra_District#/map/0'),
('Brahmanbaria', 'Brahmanbaria District (Bengali: ব্রাহ্মণবাড়িয়া জেলা, romanized: Brammôṇbaṛiya) is a district in eastern Bangladesh located in the Chittagong Division. Geographically, it is mostly farmland and is topographically part of the Gangetic Plain. It is bounded by the districts of Kishoreganj and Habiganj to the north, Narsingdi District and Narayanganj to the west, Comilla to the south, and the Indian state of Tripura to the east. It was a part of Comilla District until 15 February 1984', 'https://upload.wikimedia.org/wikipedia/commons/f/f0/Jamia_Younocia_Brahmanbaria.jpg;https://upload.wikimedia.org/wikipedia/commons/8/8d/Kullapathar_Martyrs_Memorial%2C_kasba%2C_Brahmanbaria%2C_Bangladesh_.jpg;https://upload.wikimedia.org/wikipedia/commons/3/3b/Traditional_Boat_Race%2C_Brahmanbaria.jpg;https://en.banglapedia.org/images/2/2c/BrahmanbariaDistrict.jpg'),
('Chandpur', 'Chandpur District (Bengali: চাঁদপুর জেলা) is a district in Chittagong Division, Bangladesh.[1] Established on 15 February 1984, it is famously known as the \"Home of Hilsa\" (Bengali: ইলিশের বাড়ি) due to its vast production and trade of Hilsa fish.', 'https://upload.wikimedia.org/wikipedia/commons/4/4f/Chandpur_seen_from_the_river_02.jpg;https://upload.wikimedia.org/wikipedia/commons/2/2e/%E0%A6%B0%E0%A7%82%E0%A6%AA%E0%A6%B8%E0%A6%BE_%E0%A6%9C%E0%A6%AE%E0%A6%BF%E0%A6%A6%E0%A6%BE%E0%A6%B0_%E0%A6%AC%E0%A6%BE%E0%A6%A1%E0%A6%BC%E0%A6%BF%E0%A6%B0_%E0%A6%AE%E0%A7%82%E0%A6%B2_%E0%A6%AD%E0%A6%AC%E0%A6%A8_%E0%A7%A6%E0%A7%A8.jpg;https://upload.wikimedia.org/wikipedia/commons/5/5f/BD_Chandpur_District_locator_map.svg'),
('Chittagong', 'Chittagong District (Bengali: চট্টগ্রাম জেলা), (Chittagonian: Sitang/Chatga), officially Chattogram District,[5] is a district located in south-eastern Bangladesh. It is a part of the Chittagong Division. Due to its geographical location, Chittagong is classified as a special district in Bangladesh. With its hills, sea, valleys, and forests, Chittagong is one of the most naturally beautiful regions in the country. Because of its natural beauty and diversity, it is often referred to as the \"Queen of the East\". The commercial capital of Bangladesh and the country\'s only two-dimensional city are both located in Chittagong District. In terms of establishment, this is the oldest district in Bangladesh, and by area, it is the second largest. The population of Chittagong District was 9,169,464 at the 2022 Census. The district has its own distinct language and culture. Due to its linguistic and cultural uniqueness, it is considered the most diverse district in Bangladesh. The language spoken b', 'https://upload.wikimedia.org/wikipedia/commons/1/1a/%E0%A6%86%E0%A6%A8%E0%A7%8D%E0%A6%A6%E0%A6%B0%E0%A6%95%E0%A6%BF%E0%A6%B2%E0%A7%8D%E0%A6%B2%E0%A6%BE_%E0%A6%B6%E0%A6%BE%E0%A6%B9%E0%A7%80_%E0%A6%9C%E0%A6%BE%E0%A6%AE%E0%A7%87_%E0%A6%AE%E0%A6%B8%E0%A6%9C%E0%A6%BF%E0%A6%A6_%28%E0%A6%A1%E0%A6%BE%E0%A6%A8_%E0%A6%AA%E0%A6%BE%E0%A6%B0%E0%A7%8D%E0%A6%B6%E0%A7%87%E0%A6%B0_%E0%A6%AE%E0%A6%BF%E0%A6%A8%E0%A6%BE%E0%A6%B0%29.jpg;https://upload.wikimedia.org/wikipedia/commons/6/62/Chandranath_Temple_At_Sitakunda_%286%29.jpg;https://upload.wikimedia.org/wikipedia/commons/d/d7/Mahamaya_Lake%2C_Mirsharai%2C_Chittagong%2C_Bangladesh.jpg;https://upload.wikimedia.org/wikipedia/commons/3/3b/Chittagong_District_upazila_geocode_map_-_Small_Area_Atlas_Bangladesh.svg'),
('Chuadanga', 'Chuadanga District (Bengali: চুয়াডাঙ্গা জেলা) is a district in south western Bangladesh, specifically Khulna Division, Bangladesh. It is bordered by the Indian state of West Bengal to the west, Meherpur District to the northwest, Jessore District to the south, Jhenaidah District to the east, and Kushtia District to the north. Before partition Chuadanga was one of the five subdivisions of Nadia district.', 'https://upload.wikimedia.org/wikipedia/commons/4/48/Chuadanga_Railway_Station_01.jpg;https://upload.wikimedia.org/wikipedia/commons/4/4d/Darsana_Distillery_at_Carew_%26_Co.jpg;https://upload.wikimedia.org/wikipedia/commons/5/53/BD_Chuadanga_District_locator_map.svg'),
('Comilla', 'Comilla (Bengali: কুমিল্লা), officially spelled Cumilla,[3][4] is a metropolis on the banks of the Gumti River in eastern Bangladesh. Comilla was one of the cities of ancient Bengal. It was once the capital of Tripura kingdom.[5] Comilla Airport is located in the Dulipara area of Comilla city Although it is currently replaced with Comilla Export Processing Zone (EPZ). Comilla City is a division centered city district with surrounding districts coming to Comilla in more diverse areas of work. Bibir Bazar land port is located 5 km away from Comilla city. The area of Comilla City Corporation is 53.04 square kilometers, so the surrounding areas of the main city fall under the jurisdiction of the City Corporation. The urban areas falling outside the Comilla City Corporation are considered suburbs, forming part of the metro area, which was estimated at 691,000 in 2025- a 2.98% increase from 2024.', 'https://upload.wikimedia.org/wikipedia/commons/d/d2/Cumilla_City_Night.jpg;https://upload.wikimedia.org/wikipedia/commons/c/c6/Front_view_of_Chondimura_temple%2C_Comilla_district%2C_Bangladesh.jpg;https://upload.wikimedia.org/wikipedia/commons/b/b4/Roop_Sagar_Park%2C_Comilla_2018-01-09_%286%29.jpg;https://upload.wikimedia.org/wikipedia/commons/2/2f/%E0%A6%AE%E0%A6%AF%E0%A6%BC%E0%A6%A8%E0%A6%BE%E0%A6%AE%E0%A6%A4%E0%A6%BF_%E0%A6%B0%E0%A6%BE%E0%A6%A3%E0%A7%80%E0%A6%B0_%E0%A6%95%E0%A7%81%E0%A6%A0%E0%A6%BF%E0%A6%B0_%28Maynamati_Ranir_Kuthir%29.jpg;'),
('Cox\'s Bazar', 'Cox\'s Bazar District (Bengali: কক্সবাজার জেলা) is a district in the Chittagong Division of Bangladesh.[3] It is named after the town of Cox\'s Bazar. It is located 150 kilometres (93 mi) south of Chittagong. Cox\'s Bazar is also known by the names Panowa (\"yellow flower\") and Palongkee. The modern Cox\'s Bazar derives its name from Captain Hiram Cox (died 1799), an army officer who served in British India. It is one of the fishing ports of Bangladesh, and contains one of the world\'s longest natural sea beaches (120 kilometres (75 mi) long including mud flats).', 'https://upload.wikimedia.org/wikipedia/commons/4/4f/Cox%27s_bazar_marine_drive-6.JPG;https://upload.wikimedia.org/wikipedia/en/0/03/Coxs_Bazar_Rail_Station_%28cropped%29.jpg;https://upload.wikimedia.org/wikipedia/commons/8/8c/Pink_sky_at_sea_beach.jpg'),
('Dhaka', 'Dhaka District (Bengali: ঢাকা জেলা, romanized: Ḍhākā jēlā) is a district in central Bangladesh,[5] and is the densest district in the nation. It is a part of the Dhaka Division. Dhaka, the capital of Bangladesh, rests on the eastern banks of the Buriganga River which flows from the Turag to the southern part of the district. The former Dhaka city corporation occupied only about a fifth of the area of Dhaka district until 2011 where the municipal corporation was fractionated and rearranged in North and South corporations due to being the economic, political and cultural centre of the district and also the country. Dhaka District consists of Dhaka city, Keraniganj, Nawabganj, Dohar, Savar and Dhamrai upazila. Dhaka District is an administrative entity, and like many other cities, it does not cover the modern conurbation which is Greater Dhaka, which has spilled into neighbouring districts, nor does the conurbation cover the whole district, as there are rural areas within the district.', 'https://upload.wikimedia.org/wikipedia/commons/1/17/Bangladesh_National_Parliament_House.jpg;https://upload.wikimedia.org/wikipedia/commons/b/bf/Baitul_Mukarram_National_Mosque_in_2022.16.jpg;https://upload.wikimedia.org/wikipedia/commons/9/9a/National_Martyrs%E2%80%99_Memorial_08.jpg;https://upload.wikimedia.org/wikipedia/commons/b/b0/Lalbagh_Kella_%28Lalbagh_Fort%29-12.jpg;https://upload.wikimedia.org/wikipedia/commons/a/ae/BD_Dhaka_District_locator_map.svg'),
('Dinajpur', 'Dinajpur District (Bengali: দিনাজপুর জেলা) is a district in Rangpur Division of northern Bangladesh. Dinajpur is the largest among all sixteen northern districts of Bangladesh.', 'https://upload.wikimedia.org/wikipedia/commons/7/7e/Nawabganj_National_Park_Dinajpur_3254.jpg;https://upload.wikimedia.org/wikipedia/commons/6/6e/West_side_of_Sura_Mosque.jpg;https://upload.wikimedia.org/wikipedia/commons/2/22/Dinajpur_Railway_Bridge.jpg;https://upload.wikimedia.org/wikipedia/commons/7/7e/BD_Dinajpur_District_locator_map.svg'),
('Faridpur', 'Faridpur District (Bengali: ফরিদপুর জেলা) is a district in south-central Bangladesh. It is a part of Dhaka Division. It is bounded by the Padma River to the northeast. The district was named for its headquarters, the city of Faridpur, which itself was named for Farīd-ud-Dīn Masʿūd, a 13th-century Sufi saint. A separate district was created by severing Dhaka district in 1786 and was called Dacca Jelalpur. A municipality was established in 1869. Historically, the town was known as Fatehabad. It was also called Haveli Mahal Fatehabad.', 'https://upload.wikimedia.org/wikipedia/commons/1/10/Faridpur_PatrailMoshjid_MG_2971.jpg;https://upload.wikimedia.org/wikipedia/commons/c/c2/Shikdar_barir_gombuj_2.jpg;https://upload.wikimedia.org/wikipedia/commons/2/2e/Mothurar_Deol_Faridpur.jpg;https://upload.wikimedia.org/wikipedia/commons/7/7e/BD_Faridpur_District_locator_map.svg'),
('Feni', 'Feni District (Bengali: ফেনী জেলা) is a coastal district situated in the south-east of Bangladesh, within Chittagong Division. One of Bangladesh\'s smallest districts, it is strategically located along the Dhaka–Chittagong transportation corridor. Bordered by India to the north and the Bay of Bengal to the south, it serves as the sole entry point linking Chittagong, the country\'s primary port city, to the northern districts.', 'https://upload.wikimedia.org/wikipedia/commons/9/92/Asgar_Ali_Chowdhury_Mosque.JPG;https://upload.wikimedia.org/wikipedia/commons/4/4c/Ramnagor_Chowdhury_Bari_Jame_Masjid.jpg;https://upload.wikimedia.org/wikipedia/commons/2/2a/Feni_ShathMoth_MG_3800.jpg;https://upload.wikimedia.org/wikipedia/commons/e/e4/BD_Feni_District_locator_map.svg'),
('Gaibandha', 'Gaibandha District (Bengali: গাইবান্ধা জেলা) is a district in northern Bangladesh, located within Rangpur Division. Covering an area of 2,179.27 square kilometers (841.42 sq mi), it had a population of 2,562,232 as of the 2022 census. The district\'s administrative headquarters and largest urban center is Gaibandha town. Originally established as a subdivision in 1875 under the name Bhabaniganj, it was renamed Gaibandha in the same year. On February 15, 1984, Gaibandha was officially upgraded to district status. The district is known for its agricultural production, particularly rice, jute, and vegetables, and is situated at the confluence of several major rivers, including the Jamuna, Teesta, and Brahmaputra.', 'https://en.wikipedia.org/wiki/Gaibandha#/media/File:Friendship_Centre_Gaibandha,_December_2016_07.jpg;https://upload.wikimedia.org/wikipedia/commons/f/ff/BD_Gaibandha_District_locator_map.svg;https://upload.wikimedia.org/wikipedia/commons/0/07/Fulsori_Ghat_Gaibandha.jpg'),
('Gazipur', 'Gazipur District (Bengali: গাজীপুর জেলা) is a district in central Bangladesh, that is part of the Dhaka Division. It has an area of 1806.36 km2.[1][3] It is the home district of Tajuddin Ahmad, the first Prime Minister of Bangladesh and has been a prominent centre of battles and movements throughout history. Gazipur is home to the Bishwa Ijtema (lit. \"world congregation\"), the second-largest annual Muslim gathering in the world with over 5 million attendees.[4] The district is home to numerous universities, colleges, the Gazipur Safari Park, Bhawal National Park as well as the country\'s only business park - the Hi-Tech City, Kaliakoir.', 'https://upload.wikimedia.org/wikipedia/commons/0/0a/IUT_Lake_Auditorium.jpg;https://upload.wikimedia.org/wikipedia/commons/c/cf/Bhawal_Estate.jpg;https://upload.wikimedia.org/wikipedia/commons/8/8c/Dhaka_University_of_Engineering_Technology.jpg;https://upload.wikimedia.org/wikipedia/commons/b/bf/Bangladesh_Gazipur_district_locator_map.svg'),
('Gopalganj', 'Gopalganj District (Bengali: গোপালগঞ্জ জেলা) is a district in Dhaka Division, Bangladesh.[4] The district has 1,172,415 inhabitants and its surface area is 1,490 km2. The district headquarters is also called Gopalganj. It is located on the bank of the Madhumati river and located at 23°00’47.67\" N 89°49’21.41\". It is bounded by Faridpur district on the North, Pirojpur and Bagerhat district on the South, and Barisal District on the East and Narail district on the West. Gopalganj is subdivided into five sub-districts (upazilas and thanas). This district has the highest percentage of Hindus among the districts of Bangladesh, which is about 30 percent.', 'https://upload.wikimedia.org/wikipedia/commons/8/85/%E0%A6%97%E0%A7%8B%E0%A6%AA%E0%A6%BE%E0%A6%B2%E0%A6%97%E0%A6%9E%E0%A7%8D%E0%A6%9C.jpg;'),
('Habiganj', 'Habiganj District (Bengali: হবিগঞ্জ জেলা; Bengali pronunciation: [ɦobigɔnd͡ʒ d͡ʒela]), formerly known as Habibganj District (Bengali: হাবিবগঞ্জ জেলা), is a district in north-eastern Bangladesh, located in the Sylhet Division. It was established as a district in 1984 as a successor to its subdivision status since 1867. It is named after its founder, Syed Habib Ullah, son of Syed Hedayet Ullah, who is the founder of Sultani Habeli.', 'https://upload.wikimedia.org/wikipedia/commons/0/0f/%E0%A6%89%E0%A6%9A%E0%A6%BE%E0%A6%87%E0%A6%B2_%E0%A6%B6%E0%A6%82%E0%A6%95%E0%A6%B0%E0%A6%AA%E0%A6%BE%E0%A6%B6%E0%A6%BE_%E0%A6%B6%E0%A6%BE%E0%A6%B9%E0%A7%80_%E0%A6%AE%E0%A6%B8%E0%A6%9C%E0%A6%BF%E0%A6%A6_%E0%A7%A7%E0%A7%A8.jpg;https://upload.wikimedia.org/wikipedia/commons/7/72/%E0%A6%A8%E0%A7%80%E0%A6%B2_%E0%A6%B8%E0%A6%AC%E0%A7%81%E0%A6%9C%E0%A7%87%E0%A6%B0_%E0%A6%B0%E0%A6%BE%E0%A6%9C%E0%A7%8D%E0%A6%AF_03.jpg;https://upload.wikimedia.org/wikipedia/commons/8/8f/BD_Habiganj_District_locator_map.svg'),
('Jamalpur', 'Jamalpur District (Bengali: জামালপুর জেলা) is a district in Bangladesh, and part of Mymensingh Division. It was established in 1978 during the rule of Ziaur Rahman. It has its headquarters in Jamalpur', 'https://upload.wikimedia.org/wikipedia/commons/d/d7/Zilla_Shilpakala_Academy%2C_Jamalpur_%282%29_%28cropped%29.jpg;https://en.wikipedia.org/wiki/Jamalpur_District#/media/File:Sarishabari,_Jamalpur,_Bangladesh_(31245373515).jpg;https://upload.wikimedia.org/wikipedia/commons/6/67/View_in_a_Village_of_Bangladesh.jpg;https://upload.wikimedia.org/wikipedia/commons/2/29/BD_Jamalpur_District_locator_map.svg'),
('Jessore', 'Jessore District, officially Jashore District[3][4][5] (Bengali: যশোর জেলা; Bengali pronunciation: [Jaw-shor Jela]), is a district in southwestern Bangladesh. It is bordered by India to the west, Khulna and Satkhira districts to the south, Khulna and Narail to the east, and Jhenaidah and Magura districts to the north. Jessore is the capital of the district. Jessore is the home to the ancestors of Rabindranath Tagore. Jashore was the first independent district of Bangladesh in 1971.', 'https://upload.wikimedia.org/wikipedia/commons/3/3e/Jashore_Collectorate_Building%2C_Bangladesh.jpg;https://upload.wikimedia.org/wikipedia/commons/3/30/BD_Jashore_District_locator_map.svg'),
('Jhalokati', 'Jhalokathi District, officially Jhalakathi District, (Bengali: ঝালকাঠি জেলা) is a district in southern Bangladesh.[1] It is located in the Barisal Division and covers an area of 758.06 km2. It is bounded by Barisal District to the north, Barguna district to the east and the Bishkhali river in the south, and Pirojpur district to the west. The main rivers in this district are the Bishkhali, Dhanshiri, Gabkhan, Sugandha, Jangalia, Bamanda and Bajitpur. \"পেয়ারা আর শীতলপাটি, এই নিয়ে ঝালকাঠি\" \"(Jhalokathi, The land of tasty Guava and Shitolpati)\" is the official motto of the district', 'https://upload.wikimedia.org/wikipedia/commons/d/dc/Pouro_Mini_Park_Jhalokathi%2C_Bangladesh.jpg;https://upload.wikimedia.org/wikipedia/commons/b/bd/Jhalokathi_N_S_Kamil_Madrasah_Mosque.jpg;https://upload.wikimedia.org/wikipedia/commons/e/e0/BD_Jhalokati_District_locator_map.svg'),
('Jhenaidah', 'Jhenaidah District (Bengali: ঝিনাইদহ জেলা) is a district in southwestern Bangladesh. Part of the Khulna Division, the district has an area of 1,964.77 km2 (758.60 sq mi).[3] It is bordered by Kushtia District to the north, Jessore District and West Bengal to the south, Rajbari District and Magura District to the east, and Chuadanga District and West Bengal to the west. The largest city and headquarters of this district is Jhenaidah.[4] At the beginning of the British rule, Jhenaidah was a police outpost and was turned into a thana in 1793. The Jhenaidah sub-division was established in 1862. It became a district in 1984.', 'https://upload.wikimedia.org/wikipedia/commons/c/c5/%E0%A6%9D%E0%A6%BF%E0%A6%A8%E0%A6%BE%E0%A6%87%E0%A6%A6%E0%A6%B9_%E0%A6%AA%E0%A6%BE%E0%A6%AF%E0%A6%BC%E0%A6%B0%E0%A6%BE_%E0%A6%9A%E0%A6%A4%E0%A7%8D%E0%A6%A4%E0%A7%8D%E0%A6%AC%E0%A6%B0.jpg;https://upload.wikimedia.org/wikipedia/commons/e/ee/Jhenaidah_PathagarMoshjid_20Mar14_IMG_7085.jpg;https://upload.wikimedia.org/wikipedia/commons/6/64/BD_Jhenaidah_District_locator_map.svg'),
('Joypurhat', 'Joypurhat District (Bengali: জয়পুরহাট জেলা) is a district in northern Bangladesh, and part of Rajshahi Division.', 'https://upload.wikimedia.org/wikipedia/commons/0/00/Green_City_of_Bangladesh.jpg;https://upload.wikimedia.org/wikipedia/commons/3/36/BD_Joypurhat_District_locator_map.svg'),
('Khagrachari', 'Khagrachhari District (Bengali: খাগড়াছড়ি জেলা), officially Khagrachhari Hill District, is a district in the Chittagong Division of Southeastern Bangladesh. It is a part of the Chittagong Hill Tracts region.', 'https://upload.wikimedia.org/wikipedia/commons/f/f4/Midway_to_Konglak_Hill%2C_Khagrachari%2C_Bangladesh.jpg;https://upload.wikimedia.org/wikipedia/commons/3/34/BD_Khagrachari_District_locator_map.svg;https://www.bijoy36.com/wp-content/uploads/2025/04/nnnn.jpg'),
('Khulna', 'Khulna District (Bengali: খুলনা জেলা) is a district of Bangladesh. It is located in the Khulna Division, bordered in the north by Jashore District and Narail District, in the south by the Bay of Bengal, in the east by Bagerhat District, and the west by Satkhira District.[3] It was the first sub-division of the United Bengal Province established in 1842. On 1 June 1882, by notification of the official gazette published from Kolkata, Khulna and Bagerhat sub-division of Jashore district and Satkhira sub-division of 24 Parganas district together formed the new district of Khulna.', 'https://upload.wikimedia.org/wikipedia/commons/f/f2/Khulna_Ship_Yard_LTD.jpg;https://upload.wikimedia.org/wikipedia/commons/8/8c/Panthera_tigris_tigris_45151733.jpg;https://upload.wikimedia.org/wikipedia/commons/b/b9/BD_Khulna_District_locator_map.svg'),
('Kishoreganj', 'Kishoreganj District (Bengali: কিশোরগঞ্জ জেলা) is a district in Dhaka Division, Bangladesh. The establishment of the Kishorganj began with 2495.07 km2 of land requisition from Mymensingh district to form Kishoreganj District. Earlier it was a mahakuma (sub-division) under Mymensingh district. Kishorganj consists of Ten municipalities, 13 upazilas, 105 union parishads, 39 wards, 145 mahallas, 946 mouzas, and 1775 villages', 'https://upload.wikimedia.org/wikipedia/commons/8/80/Mosque_of_Junglebari_Fort.jpg;https://upload.wikimedia.org/wikipedia/commons/6/68/%E0%A6%B8%E0%A7%88%E0%A6%AF%E0%A6%BC%E0%A6%A6_%E0%A6%A8%E0%A6%9C%E0%A6%B0%E0%A7%81%E0%A6%B2_%E0%A6%87%E0%A6%B8%E0%A6%B2%E0%A6%BE%E0%A6%AE_%E0%A6%B8%E0%A7%87%E0%A6%A4%E0%A7%81_09.jpg;https://upload.wikimedia.org/wikipedia/commons/9/9f/BD_Kishoreganj_District_locator_map.svg'),
('Kurigram', 'Kurigram District (Bengali: কুড়িগ্রাম জেলা) is a district of Bangladesh in Rangpur Division. The district is located in northern Bangladesh along the country\'s border with India.[4] Under British rule, the area was organized as a mahakuma and was not established as a district until 1984 under Chief Martial Law Administrator, Hussain Muhammad Ershad\'s decentralization programme.', 'https://upload.wikimedia.org/wikipedia/commons/a/a1/Chandamari_mosqu1.jpg;https://upload.wikimedia.org/wikipedia/commons/c/cf/Munshibari.jpg;https://upload.wikimedia.org/wikipedia/commons/3/3d/BD_Kurigram_District_locator_map.svg'),
('Kushtia', 'Kushtia District (Bengali: কুষ্টিয়া জেলা; pronounced [kuʃʈi̯a‿d͡ʒela] ⓘ) is a district in the Khulna administrative division of western Bangladesh. Kushtia is the second largest municipality in Bangladesh and the eleventh largest city in the country. Kushtia has existed as a separate district since the partition of India.[5] Prior to that, Kushtia was name of a subdivision of Nadia district. Kushtia is the birthplace of many historical figures including Mir Mosharraf Hossain (1847–1912),[6] Bagha Jatin (1879–1915)[7] Akshay Kumar Maitreya(1861 – 1930) and Lalon (1774–1890).[8] Nobel laureate poet Rabindranath Tagore lived his early life at Shelaidaha, a village in the district.[9] The proclamation of Bangladeshi independence occurred at Baidyanathtala on 17 April 1971 soon after a brief occupation by the Pakistani Army since 1 April, during Operation Searchlight and the Bangladesh genocide.', 'https://upload.wikimedia.org/wikipedia/commons/b/b4/IMG_20180504_175752_HDR.jpg;https://upload.wikimedia.org/wikipedia/commons/9/9b/Shelaidaha_kuthibadi_.jpg;https://upload.wikimedia.org/wikipedia/commons/b/b8/Nice_Fruits_tree%2C%2C_in_Bharamara%2C_Kustia._Bangladesh.jpg;https://upload.wikimedia.org/wikipedia/commons/1/1c/BD_Kushtia_District_locator_map.svg'),
('Lakhsmipur', 'Lakshmipur District (Bengali: লক্ষ্মীপুর জেলা; Bengali pronunciation: [lokʰːiˈpur]) is a district in Bangladesh with an area of 1,440 km2. It is bordered by Chandpur to the north, Bhola and Noakhali districts to the south, Noakhali to the east, and Barisal and Bhola districts to the west. Lakshmipur was part of Noakhali until 15 February 1984, when the western part of Noakhali was reorganised from Lakshmipur subdivision into Lakshmipur district to improve administrative efficiency.', 'https://upload.wikimedia.org/wikipedia/commons/c/c4/%E0%A6%A4%E0%A6%BF%E0%A6%A4%E0%A6%BE_%E0%A6%96%E0%A6%BE%E0%A6%81_%E0%A6%AE%E0%A6%B8%E0%A6%9C%E0%A6%BF%E0%A6%A6%E0%A7%87%E0%A6%B0_%E0%A6%B8%E0%A6%AE%E0%A7%8D%E0%A6%AE%E0%A7%81%E0%A6%96%E0%A6%AD%E0%A6%BE%E0%A6%97_%E0%A7%A8.jpg;https://upload.wikimedia.org/wikipedia/commons/c/ca/Lower_Ganges_in_Lakshmipur%2C_Bangladesh.jpg;https://upload.wikimedia.org/wikipedia/commons/b/b2/BD_Lakshmipur_District_locator_map.svg'),
('Lalmonirhat', 'Lalmonirhat District (Bengali: লালমনিরহাট জেলা) is a District, situated at the northern border of Bangladesh. It is a part of the Rangpur Division.[2] Lalmonirhat mahakuma was established as a district on 1 February 1984. To the north of Lalmonirhat lie Cooch Behar and Jalpaiguri districts of West Bengal; to the south lies Rangpur, to the east lie Kurigram and Cooch Behar; and to the west of lie Rangpur and Nilphamari District. The international border line of Lalmonirhat district is 281.6 km long.', 'https://upload.wikimedia.org/wikipedia/commons/1/1c/Tista_Barrage_-_panoramio_%284%29.jpg;https://upload.wikimedia.org/wikipedia/commons/7/7b/Tin_Bigha_Corridor_%28%E0%A6%A4%E0%A6%BF%E0%A6%A8%E0%A6%AC%E0%A6%BF%E0%A6%98%E0%A6%BE_%E0%A6%95%E0%A6%B0%E0%A6%BF%E0%A6%A1%E0%A6%B0%29_144.jpg;https://upload.wikimedia.org/wikipedia/commons/f/f0/Tista_River_%2834824169324%29.jpg;https://upload.wikimedia.org/wikipedia/commons/0/04/BD_Lalmonirhat_District_locator_map.svg'),
('Madaripur', 'Madaripur District (Bengali: মাদারীপুর জেলা) is a district in central Bangladesh and a part of the Dhaka Division.', 'https://upload.wikimedia.org/wikipedia/commons/1/16/Madaripur_RajaramMondir_19Feb16_MG_2664.jpg;https://upload.wikimedia.org/wikipedia/commons/1/14/BD_Madaripur_District_locator_map.svg'),
('Magura', 'Magura District (Bengali: মাগুরা জেলা) is a district in southwestern Bangladesh, and situated 176 kilometers from Dhaka. It is located in Khulna Division.', 'https://upload.wikimedia.org/wikipedia/commons/d/dc/Gorai_Bridge_34.jpg;https://upload.wikimedia.org/wikipedia/commons/b/bc/BD_Magura_District_locator_map.svg'),
('Manikganj', 'Manikganj District (Bengali: মানিকগঞ্জ জেলা, romanized: Mānikgoñj Jela; Bengali pronunciation: [mɑnɪkˈɡondʒ]) is a district in central Bangladesh and part of the Dhaka Division. It was established in 1845 as a subdivision of Faridpur District, then in 1853, it was transferred to Dhaka District for administrative purposes. Finally in 1984, Manikganj was declared a full district', 'https://upload.wikimedia.org/wikipedia/commons/2/2a/Baliati_Palace%2C_Saturia%2C_Manikganj_%2832%29.jpg;https://upload.wikimedia.org/wikipedia/commons/d/d2/Ishwar_chandra_high_school%2C_Manikgonj-2.jpg;https://upload.wikimedia.org/wikipedia/commons/3/32/Teota_Jomidar_Bari_and_Navaratna_Temple_by_Nasir_Khan.jpg;https://upload.wikimedia.org/wikipedia/commons/9/9d/BD_Manikganj_District_locator_map.svg'),
('Meherpur', 'Meherpur District (Bengali: মেহেরপুর জেলা) is a northwestern district of Khulna Division in southwestern Bangladesh. It is bordered by West Bengal, India in the west, and by the Bangladeshi districts of Kushtia and Chuadanga to the east.[4] Pre-independence Meherpur was a subdivision of Nadia district.[5] The district has an area of 716.08 square kilometres (276.48 sq mi).', 'https://upload.wikimedia.org/wikipedia/commons/8/89/BD_Meherpur_District_locator_map.svg'),
('Moulvibazar', 'Moulvibazar District (Bengali: মৌলভীবাজার জেলা), formerly South Sylhet Subdivision [2][3] is the southeastern district of Sylhet Division in northeastern Bangladesh, named after the town of Moulvibazar. It is bordered by the Indian states of Tripura and Assam to the south and east, respectively; by the Bangladeshi districts of Habiganj to the west and Sylhet to the north.', 'https://upload.wikimedia.org/wikipedia/commons/9/9d/Hum_Hum_Waterfall_%283%29.jpg;https://upload.wikimedia.org/wikipedia/commons/1/15/%E0%A6%97%E0%A6%B9%E0%A7%80%E0%A6%A8_%E0%A6%85%E0%A6%B0%E0%A6%A8%E0%A7%8D%E0%A6%AF.jpg;https://upload.wikimedia.org/wikipedia/commons/5/5a/%E0%A6%AA%E0%A7%83%E0%A6%A4%E0%A7%8D%E0%A6%A5%E0%A6%BF%E0%A6%AE%E0%A6%AA%E0%A6%BE%E0%A6%B6%E0%A6%BE_%E0%A6%9C%E0%A6%AE%E0%A6%BF%E0%A6%A6%E0%A6%BE%E0%A6%B0_%E0%A6%AC%E0%A6%BE%E0%A6%A1%E0%A6%BC%E0%A6%BF%E0%A6%B0_%E0%A6%B6%E0%A6%BF%E0%A6%AF%E0%A6%BC%E0%A6%BE_%E0%A6%AE%E0%A6%B8%E0%A6%9C%E0%A6%BF%E0%A6%A6.jpg;https://upload.wikimedia.org/wikipedia/commons/a/a1/BD_Moulvibazar_District_locator_map.svg'),
('Munshiganj', 'Munshiganj District (Bengali: মুন্সীগঞ্জ জেলা) is a district of Dhaka Division. It is located in central Bangladesh. This region is also historically known as Bikrampur.', 'https://upload.wikimedia.org/wikipedia/commons/d/d9/Idrakpur_kella_07.jpg;https://upload.wikimedia.org/wikipedia/commons/8/8c/Bangladesh_Munshiganj_district_locator_map.svg'),
('Mymensingh', 'Mymensingh District (Bengali: ময়মনসিংহ জেলা) is a district in Mymensingh Division Bangladesh, and is bordered in the north by Meghalaya, India and the Garo Hills, in the south by Gazipur District, in the east by the districts of Netrokona and Kishoreganj and in the west by the districts of Sherpur, Jamalpur and Tangail.[4] Mymensingh is the 8th administrative divisional headquarters and 12th city corporation of Bangladesh. According to Ministry of Public Administration, Mymensingh is ranked 4th in district status. The density of Mymensingh city is 44,458/km2 (115,150/sq mi) which is the second most densely populated city in Bangladesh. Mymensingh attracts 25 percent of health tourists visiting Bangladesh. It was once known as the largest district of the Indian subcontinent. Mymensingh town is the district headquarters.', 'https://upload.wikimedia.org/wikipedia/commons/9/90/A_front_view_of_Shashi_Lodge_4.jpg;https://upload.wikimedia.org/wikipedia/commons/a/a7/JKKNIU_Top_View.jpg;https://upload.wikimedia.org/wikipedia/commons/0/0b/Rayhan_29_Sep_17_08.png;https://en.wikipedia.org/wiki/Mymensingh_District#/media/File:BD_Mymensingh_District_locator_map.svg'),
('Naogaon', 'Naogaon District (Bengali: নওগাঁ জেলা) is a district in northern Bangladesh, and part of Rajshahi Division.[4] It is named after its headquarters, the city of Naogaon in Naogaon Sadar Upazila.', 'https://upload.wikimedia.org/wikipedia/commons/9/9f/NaogaonDistrict_Bangladesh.jpg;https://upload.wikimedia.org/wikipedia/commons/2/28/BD_Naogaon_District_locator_map.svg'),
('Narail', 'Narail District (Bengali: নড়াইল জেলা) is a district in south-western Bangladesh. It is a part of Khulna Division.', 'https://upload.wikimedia.org/wikipedia/commons/7/7c/BD_Narail_District_locator_map.svg'),
('Narayanganj', 'Narayanganj District (Bengali: নারায়ণগঞ্জ জেলা, romanized: nārāẏoṇgoñjo jela) is a district in central Bangladesh which is a part of Dhaka Division.[3] It is the smallest district in Bangladesh. It is home to the ancient city of one of the oldest industrial districts in the country. The district lies on the banks of the Shitalakshya River and the Meghna River. It is an industrial hub and plays an important part in the country\'s jute trade, plant processing and sector. It is nicknamed the \"Dundee of Bangladesh\" due to the presence of many jute mills.', 'https://upload.wikimedia.org/wikipedia/commons/8/86/DG_36_-08_SONA_KANDA_FORT_16_CE_NTURY_MUGAL_ERA_BANDAR_NARAYAN_GONJ_IMG_5467.jpg;https://upload.wikimedia.org/wikipedia/commons/4/48/%E0%A6%AA%E0%A6%BE%E0%A6%A8%E0%A6%BE%E0%A6%AE_%E0%A6%A8%E0%A6%97%E0%A6%B0_03.jpg;https://upload.wikimedia.org/wikipedia/commons/9/96/Boro_Sardar_Bari_-_10.jpg;https://upload.wikimedia.org/wikipedia/commons/e/e1/BD_Narayanganj_District_locator_map.svg'),
('Narsingdi', 'Narsingdi District (Bengali: নরসিংদী জেলা) is a district in central Bangladesh. It is located 50 km north-east of Dhaka, the Bangladeshi capital. It is a part of Dhaka Division.[3] The district is famous for its textile craft industry. Narsingdi is bordered by Kishoreganj in the north and north-east, Brahmanbaria in the east and south-east, Narayanganj in the south and south-west and Gazipur in the west.', 'https://upload.wikimedia.org/wikipedia/commons/1/1a/%E0%A6%AA%E0%A6%BE%E0%A6%B0%E0%A7%81%E0%A6%B2%E0%A6%BF%E0%A6%AF%E0%A6%BC%E0%A6%BE_%E0%A6%B6%E0%A6%BE%E0%A6%B9%E0%A7%80_%E0%A6%AE%E0%A6%B8%E0%A6%9C%E0%A6%BF%E0%A6%A6_03_%28cropped%29.jpg;https://upload.wikimedia.org/wikipedia/commons/3/35/%E0%A6%B2%E0%A6%95%E0%A7%8D%E0%A6%B7%E0%A6%A3_%E0%A6%B8%E0%A6%BE%E0%A6%B9%E0%A6%BE%E0%A6%B0_%E0%A6%9C%E0%A6%AE%E0%A6%BF%E0%A6%A6%E0%A6%BE%E0%A6%B0_%E0%A6%AC%E0%A6%BE%E0%A6%A1%E0%A6%BC%E0%A6%BF.jpg;https://upload.wikimedia.org/wikipedia/commons/c/c3/Central_Jame_Mosque_of_Belabo_in_Narsingdi%2C_Bangladesh_%28cropped%29.jpg;https://upload.wikimedia.org/wikipedia/commons/9/99/BD_Narsingdi_District_locator_map.svg'),
('Natore', 'Natore District (Bengali: নাটোর জেলা) is a district in Rajshahi Division located in northern Bangladesh. It borders the metropolitan city of Rajshahi and used to be a part of Rajshahi District.', 'https://upload.wikimedia.org/wikipedia/commons/a/ad/Uttara_Gonobhaban_01-Porag61.jpg;https://upload.wikimedia.org/wikipedia/commons/9/9b/Chalon_Bil%2C_Natore.JPG;https://upload.wikimedia.org/wikipedia/commons/5/50/BD_Natore_District_locator_map.svg'),
('Nawabganj', 'Chapai Nawabganj or Chapainawabganj District (Bengali: চাঁপাইনবাবগঞ্জ জেলা), often colloquially simply called Chapai (Bengali: চাঁপাই) is a district of the Rajshahi Division. It is located in the north-western part of Bangladesh. The north and western-part of Chapainawabganj is bounded by Malda and Murshidabad districts of India, the east by Naogaon District, and south-east by Rajshahi District.', 'https://upload.wikimedia.org/wikipedia/commons/c/ce/BD_Chapai_Nawabganj_District_locator_map.svg;https://upload.wikimedia.org/wikipedia/commons/7/7e/Chapai_%E0%A6%8F%E0%A6%B0_%E0%A6%9B%E0%A7%8B%E0%A6%9F_%E0%A6%B8%E0%A7%8B%E0%A6%A8%E0%A6%BE%E0%A6%AE%E0%A6%B8%E0%A6%9C%E0%A6%BF%E0%A6%A6.jpg;https://upload.wikimedia.org/wikipedia/commons/3/3e/%E0%A6%A4%E0%A6%BE%E0%A6%B9%E0%A6%96%E0%A6%BE%E0%A6%A8%E0%A6%BE.jpg'),
('Netrakone', 'Netrokona District, also spelt Netrakona District (Bengali: নেত্রকোণা জেলা), is a district of Mymensingh Division in north-eastern Bangladesh.', 'https://upload.wikimedia.org/wikipedia/commons/c/ca/Beautiful_Durgapur.jpg;https://upload.wikimedia.org/wikipedia/commons/a/a1/%E0%A6%95%E0%A7%87%E0%A6%A8%E0%A7%8D%E0%A6%A6%E0%A7%81%E0%A6%AF%E0%A6%BC%E0%A6%BE%E0%A6%B0_%E0%A6%B0%E0%A7%8B%E0%A6%AF%E0%A6%BC%E0%A6%BE%E0%A6%87%E0%A6%B2_%E0%A6%AC%E0%A6%BE%E0%A6%A1%E0%A6%BC%E0%A6%BF_%E0%A6%97%E0%A7%8D%E0%A6%B0%E0%A6%BE%E0%A6%AE%E0%A7%87_%E0%A6%B0%E0%A7%8B%E0%A6%AF%E0%A6%BC%E0%A6%BE%E0%A6%87%E0%A6%B2_%E0%A6%A6%E0%A7%81%E0%A6%B0%E0%A7%8D%E0%A6%97_%E0%A6%85%E0%A6%AC%E0%A6%B8%E0%A7%8D%E0%A6%A5%E0%A6%BF%E0%A6%A4.jpg;https://upload.wikimedia.org/wikipedia/commons/d/da/Birishiri_Durgapur_Netrokona.jpg;https://upload.wikimedia.org/wikipedia/commons/7/7d/BD_Netrokona_District_locator_map.svg'),
('Nilphamari', 'Nilphamari District (Bengali: নীলফামারী জেলা) is a district in Northern Bangladesh. It is a part of Rangpur Division. It is about 350 kilometers to the northwest of the capital Dhaka. It has an area of 1,580.85 square kilometres (610.37 sq mi). Nilphamari is bounded by Rangpur and Lalmonirhat in east, Rangpur and Dinajpur in south, Dinajpur and Panchagarh in west, Cooch Behar of India in north.[3] The headquarters of the district is in Nilphamari city, which is widely regarded as the industrial city of Northern Bangladesh. Saidpur which is major business center of the district also serves as connecting hub of Rangpur.', 'https://upload.wikimedia.org/wikipedia/commons/6/60/%E0%A6%9A%E0%A6%BF%E0%A6%A8%E0%A6%BF_%E0%A6%AE%E0%A6%B8%E0%A6%9C%E0%A6%BF%E0%A6%A6.jpg;https://upload.wikimedia.org/wikipedia/commons/e/ec/Kangchenjunga_From_Teesta_Barrage.jpg;https://upload.wikimedia.org/wikipedia/commons/c/c8/Saidpurairport-renovated.jpg;https://upload.wikimedia.org/wikipedia/commons/c/c9/BD_Nilphamari_District_locator_map.svg'),
('Noakhali', 'Noakhali District (Bengali: নোয়াখালী জেলা), historically known as Bhulua[3] (Bengali: ভুলুয়া), is a district in southeastern Bangladesh, located in Chattogram Division.[4][5] It was established as a district in 1821, and officially named Noakhali in 1868. The district\'s administrative center is situated in the town of Maijdee, governed by Noakhali municipality, within Noakhali Sadar Upazila.[6] Notably, Noakhali is the only district in Bangladesh whose capital city does not share the district\'s name.', 'https://upload.wikimedia.org/ wikipedia/commons/d/dc/Bazra_Shahi_Mosque_2.jpg;https://upload.wikimedia.org/wikipedia/commons/0/0a/Miah_Bari_Jame_Masjid;https://upload.wikimedia.org/wikipedia/commons/2/25/BD_Noakhali_District_locator_map.svg%2C_Nolua%2C_Senbagh%2C_Noakhali.jpg;https://upload.wikimedia.org/wikipedia/commons/5/58/Ramjan_Mia_Mosque_2.jpg;'),
('Pabna', 'Pabna District (Bengali: পাবনা জেলা) is a district in west central Bangladesh. It is a geographically and economically important district. Its administrative capital is the eponymous Pabna town. The main five rivers of this district are: Padma, Jamuna, Baral, Atrai and Chiknai.', 'https://upload.wikimedia.org/wikipedia/commons/c/c7/Ruppur_Nuclear_Power_Plant_%2C_Ruppur%2C_Pabna.jpg;https://upload.wikimedia.org/wikipedia/commons/4/42/Lalon_shah_bridge.jpg;https://upload.wikimedia.org/wikipedia/commons/9/97/Hardinge_Bridge_Full_view.jpg;https://upload.wikimedia.org/wikipedia/commons/0/01/BD_Pabna_District_locator_map.svg'),
('Panchagargh', 'Panchagarh District (Bengali: পঞ্চগড় জেলা) is a district of the Rangpur Division in Northern Bangladesh. Panchagarh is the northernmost district of Bangladesh. It lies between 26º00\' and 26º38\' north latitudes and between 88º19\' and 88º49\' east longitudes. It was established as a district on 1 February 1984.', 'https://upload.wikimedia.org/wikipedia/commons/9/9e/Kanchenjunga_view_from_Bangladesh.jpg;https://upload.wikimedia.org/wikipedia/commons/0/0a/Beautifull_Mirzapur_Mosque.jpg;https://upload.wikimedia.org/wikipedia/commons/3/3b/Tea_Garden_at_Tetulia.jpg;https://upload.wikimedia.org/wikipedia/commons/3/31/BD_Panchagarh_District_locator_map.svg'),
('Patuakhali', 'Patuakhali District (Bengali: পটুয়াখালী জেলা, romanized: Pôṭuakhali jela) is a district in south-central Bangladesh in Barisal Division. This district is the main entrance for the beach of Kuakata.', 'https://upload.wikimedia.org/wikipedia/commons/7/75/Kuakata_a_panoramic_sea_beach.jpg;https://upload.wikimedia.org/wikipedia/commons/6/6e/Beautiful_Kuakata_Beach.jpg;https://upload.wikimedia.org/wikipedia/commons/6/6b/BD_Patuakhali_District_locator_map.svg;'),
('Pirojpur', 'Pirojpur District (Bengali: পিরোজপুর জেলা) is a district in south-western Bangladesh. It is a part of Barisal Division.', 'https://upload.wikimedia.org/wikipedia/commons/3/3e/Momin_Mosque_after_restoration.jpg;https://upload.wikimedia.org/wikipedia/commons/0/06/Vimruli_Floating_Market_at_Shorupkhathi_in_Pirojpur_District.jpg;https://upload.wikimedia.org/wikipedia/commons/1/15/BD_Pirojpur_District_locator_map.svg'),
('Rajbari', 'Rajbari District (Bengali: রাজবাড়ী জেলা) is a district in central Bangladesh, located in Dhaka Division.', 'https://upload.wikimedia.org/wikipedia/commons/1/12/Beside_Railway_in_Rajbari.JPG;https://upload.wikimedia.org/wikipedia/commons/5/52/BD_Rajbari_District_locator_map.svg'),
('Rajshahi', 'ajshahi (Bengali: রাজশাহী, pronounced [radʒ.ʃaɦi] ⓘ) is a metropolitan city and a major urban, administrative, commercial and educational centre of Bangladesh. It is also the administrative seat of the eponymous division and district. It is also the largest city of North Bengal. Located on the north bank of the Padma River, near the Bangladesh–India border, the city is surrounded by the satellite towns of Nowhata and Katakhali of Paba Upazila, which together build an urban agglomeration of about 1 million population', 'https://en.wikipedia.org/wiki/Rajshahi#/media/File:Rajshahi_city_(3).jpg;https://upload.wikimedia.org/wikipedia/commons/0/08/Varendra_Research_Museum_10.jpg;https://upload.wikimedia.org/wikipedia/commons/e/ee/Bangladesh_Rajshahi_district_locator_map.svg'),
('Rangamati', '', 'https://upload.wikimedia.org/wikipedia/commons/1/1f/Sajek_Valley_01.jpg;https://upload.wikimedia.org/wikipedia/commons/b/b8/BD_Rangamati_District_locator_map.svg;'),
('Rangpur', 'Rangpur (/rɒŋpʊər/; Bengali: রংপুর, romanized: Rongpur; pronounced [rɔŋpuɾ] ⓘ) is a major metropolitan city in Bangladesh. This city serves as the administrative center of the Rangpur Division. It is strategically located on the banks of the Ghaghat River and near the Teesta River.[4] It is the second-largest city corporation in Bangladesh.', 'https://upload.wikimedia.org/wikipedia/commons/5/5d/Tajhat_Rajbari_-_Side_View_%28cropped%29.jpg;https://upload.wikimedia.org/wikipedia/commons/9/98/Rangpur_Town_Hall.jpg;https://upload.wikimedia.org/wikipedia/commons/2/29/Rangpur_City_Corporation_in_Rangpur_division_%28Bangladesh%29.svg'),
('Satkira', 'Satkhira District (Bengali: সাতক্ষীরা জেলা; lit. \'Seven cucumbers\') is a district in southwestern Bangladesh and is part of Khulna Division. It lies along the border with West Bengal, India. It is on the bank of the Arpangachhia River. The largest city and headquarters of this district is Satkhira.', 'https://upload.wikimedia.org/wikipedia/commons/6/64/%E0%A6%A4%E0%A7%87%E0%A6%A4%E0%A7%81%E0%A6%B2%E0%A6%BF%E0%A6%AF%E0%A6%BC%E0%A6%BE_%E0%A6%9C%E0%A6%BE%E0%A6%AE%E0%A7%87_%E0%A6%AE%E0%A6%B8%E0%A6%9C%E0%A6%BF%E0%A6%A6_03.jpg;https://upload.wikimedia.org/wikipedia/commons/b/be/%E0%A6%B8%E0%A7%81%E0%A6%A8%E0%A7%8D%E0%A6%A6%E0%A6%B0%E0%A6%AC%E0%A6%A8%2C%E0%A6%B8%E0%A6%BE%E0%A6%A4%E0%A6%95%E0%A7%8D%E0%A6%B7%E0%A7%80%E0%A6%B0%E0%A6%BE.jpg;https://upload.wikimedia.org/wikipedia/commons/d/db/BD_Satkhira_District_locator_map.svg'),
('Shariatpur', 'Shariatpur District (Bengali: শরিয়তপুর জেলা) is a district in Dhaka Division of central Bangladesh.[3] Shariatpur is named after the Islamic revivalist, Haji Shariatullah.', 'https://upload.wikimedia.org/wikipedia/commons/0/07/Chishtinagar.jpg;https://upload.wikimedia.org/wikipedia/commons/e/ee/%E0%A6%89%E0%A6%A6%E0%A7%8D%E0%A6%AC%E0%A7%8B%E0%A6%A7%E0%A6%A8%E0%A7%87%E0%A6%B0_%E0%A6%86%E0%A6%97%E0%A7%87%E0%A6%B0_%E0%A6%A6%E0%A6%BF%E0%A6%A8%E0%A7%87_%E0%A6%AA%E0%A6%A6%E0%A7%8D%E0%A6%AE%E0%A6%BE_%E0%A6%B8%E0%A7%87%E0%A6%A4%E0%A7%81.jpg;https://upload.wikimedia.org/wikipedia/commons/a/a9/BD_Shariatpur_District_locator_map.svg'),
('Sherpur', 'Sherpur District (Bengali: শেরপুর জেলা) is a district in northern Bangladesh. It is a part of Mymensingh Division. Sherpur District was a sub-division of Jamalpur District before 1984. It was upgraded to a district on February 22, 1984 under Hussain Muhammad Ershad\'s decentralization programme. Sherpur City is located about 197–199 kilometres (122–124 mi) north of Dhaka, the capital of Bangladesh.', 'https://upload.wikimedia.org/wikipedia/commons/5/51/Mai_Saheba_Mosque_-_2.jpg;https://upload.wikimedia.org/wikipedia/commons/9/93/%E0%A6%98%E0%A6%BE%E0%A6%98%E0%A6%A1%E0%A6%BC%E0%A6%BE_%E0%A6%96%E0%A6%BE%E0%A6%A8_%E0%A6%AC%E0%A6%BE%E0%A6%A1%E0%A6%BC%E0%A6%BF_%E0%A6%9C%E0%A6%BE%E0%A6%AE%E0%A7%87_%E0%A6%AE%E0%A6%B8%E0%A6%9C%E0%A6%BF%E0%A6%A6%E0%A7%87%E0%A6%B0_%E0%A6%A1%E0%A6%BE%E0%A6%A8_%E0%A6%AA%E0%A6%BE%E0%A6%B6.jpg;https://upload.wikimedia.org/wikipedia/commons/5/58/BD_Sherpur_District_locator_map.svg'),
('Sirajganj', 'Sirajganj District (Bengali: সিরাজগঞ্জ জেলা) is a district in North Bengal, Bangladesh, it is located in Rajshahi Division.[4] It is the 25th largest district by area and 9th largest district by population in Bangladesh. It is known as the gateway to North Bengal.  Its administrative headquarter is Sirajganj. It is famous for its hand-loom cottage industries. In 1885, Sirajganj emerged as a thana. Formerly under Mymensingh District in Dacca Division, it was transferred to Pabna District on 15 February 1866.[5] It was upgraded to become a subdivision of Pabna in 1885. In 1984, it was upgraded to a district.', 'https://upload.wikimedia.org/wikipedia/commons/a/ad/Al-Aman_Bahela_Khatun_Mosque_30.jpg;https://upload.wikimedia.org/wikipedia/commons/1/15/Shahjadpur_Dargah_Mosque_03.jpg;https://upload.wikimedia.org/wikipedia/commons/0/0b/%E0%A6%AF%E0%A6%AE%E0%A7%81%E0%A6%A8%E0%A6%BE%E0%A6%B0_%E0%A6%B6%E0%A6%BE%E0%A6%A8%E0%A7%8D%E0%A6%A4_%E0%A6%AA%E0%A7%8D%E0%A6%B0%E0%A6%95%E0%A7%83%E0%A6%A4%E0%A6%BF.jpg;https://upload.wikimedia.org/wikipedia/commons/3/3f/BD_Sirajganj_District_locator_map.svg'),
('Sunamganj', 'Sunamganj District (Bengali: সুনামগঞ্জ জেলা), is a district located in north-eastern Bangladesh in Sylhet Division', 'https://upload.wikimedia.org/wikipedia/commons/3/33/Tanguar_haor_at_dawn_2.jpg;https://upload.wikimedia.org/wikipedia/commons/4/45/%E0%A6%9F%E0%A7%87%E0%A6%95%E0%A7%87%E0%A6%B0%E0%A6%98%E0%A6%BE%E0%A6%9F-%E0%A7%AA.jpg;https://upload.wikimedia.org/wikipedia/commons/e/e5/BD_Sunamganj_District_locator_map.svg'),
('Sylhet', 'Sylhet District (Bengali: সিলেট জেলা), located in north-east Bangladesh, is one of the four districts in Sylhet Division, which contains Sylhet, the regional capital.', 'https://upload.wikimedia.org/wikipedia/commons/4/4d/Jaflong_Sylhet.jpg;https://upload.wikimedia.org/wikipedia/commons/2/29/Beautiful_Bangladesh_2.jpg;https://upload.wikimedia.org/wikipedia/commons/d/d6/Shah_Jalal_Mazar_%2803%29.jpg;https://upload.wikimedia.org/wikipedia/commons/5/50/BD_Sylhet_District_locator_map.svg'),
('Tangail', 'Tangail District (Bengali: টাঙ্গাইল জেলা, romanized: Ṭāṅgāil Jēlā) is a district (zila) in the central region of Bangladesh. The establishment of the Tangail began with 3269 square kilometres of land requisitioned from Mymensingh. Earlier it was a Mahakuma of Mymensingh district. The district consists of 237 square kilometers of the prior mahakuma and with 3,269 square kilometers of land from Mymensingh district. It is the largest district of Dhaka Division by area and second largest by population (after Dhaka district). The population of Tangail zila is about 4 million and its area is 3,414.28 square kilometres (1,318.26 sq mi).[3] The main city of the district is Tangail. It is surrounded by Jamalpur District on the north, Dhaka and Manikganj Districts on the south, Mymensingh and Gazipur on the east, and Sirajganj on the west.', 'https://upload.wikimedia.org/wikipedia/commons/0/09/201_Dome_Mosque_-_48.jpg;https://upload.wikimedia.org/wikipedia/commons/1/14/DG_38_-_08_LAND_LORD_HOUSE_MADE_BY_BABU_UPENDRA_MOHAN_ROY_LATE_18_CENTURY_PAKUTIA_TANGAIL_IM6.jpg;https://upload.wikimedia.org/wikipedia/commons/f/f5/BD_Tangail_District_locator_map.svg');
INSERT INTO `district` (`District_name`, `description`, `imagePath`) VALUES
('Thakurgaon', 'Thakurgaon District (Bengali: ঠাকুরগাঁও জেলা) is a district in northwestern Bangladesh. It is part of Rangpur Division and borders India to the west.[3] It was established as a mahakuma in 1860 consisting of 7 thanas named Thakurgaon sadar, Baliadangi, Pirganj, Ranishankail, Haripur, Bhulli and Ruhia. In 1947, it was re-established as a mahakuma including 3 thanas of Jalpaiguri and a thana of Kochbihar of India. In 1981, Atwari was included in the new Panchagarh District and the area was shrunk in just 5 thanas. It was established as a district on 1 February 1984', 'https://upload.wikimedia.org/wikipedia/commons/3/38/%E0%A6%AC%E0%A6%BE%E0%A6%B2%E0%A6%BF%E0%A6%AF%E0%A6%BC%E0%A6%BE_%E0%A6%AE%E0%A6%B8%E0%A6%9C%E0%A6%BF%E0%A6%A6.jpg;https://en.wikipedia.org/wiki/Thakurgaon_District#/media/File:Over_view_the_biggest_mango_tree_in_asia_situated_at_Thakurgaon_in_bangladesh.png;https://upload.wikimedia.org/wikipedia/commons/0/0d/BD_Thakurgaon_District_locator_map.svg');

-- --------------------------------------------------------

--
-- Table structure for table `district wise production of crop`
--

CREATE TABLE `district wise production of crop` (
  `District name` varchar(20) NOT NULL,
  `Area` decimal(10,5) DEFAULT 0.00000,
  `production` decimal(10,5) DEFAULT 0.00000,
  `Financial Year` varchar(20) NOT NULL,
  `Year midpoint` decimal(5,2) NOT NULL,
  `Crop name` varchar(100) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- --------------------------------------------------------

--
-- Table structure for table `year wise crop production`
--

CREATE TABLE `year wise crop production` (
  `Financial Year` varchar(20) NOT NULL,
  `year_midpoint` decimal(5,1) NOT NULL,
  `crop_name` varchar(100) NOT NULL,
  `crop_type` varchar(100) NOT NULL,
  `area` decimal(10,5) DEFAULT 0.00000,
  `Total production` decimal(10,10) DEFAULT 0.0000000000,
  `Yield Rate` decimal(10,10) DEFAULT 0.0000000000
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

--
-- Indexes for dumped tables
--

--
-- Indexes for table `crops`
--
ALTER TABLE `crops`
  ADD PRIMARY KEY (`crop name`);

--
-- Indexes for table `district`
--
ALTER TABLE `district`
  ADD PRIMARY KEY (`District_name`);

--
-- Indexes for table `district wise production of crop`
--
ALTER TABLE `district wise production of crop`
  ADD KEY `Crop name` (`Crop name`);

--
-- Indexes for table `year wise crop production`
--
ALTER TABLE `year wise crop production`
  ADD KEY `crop_name` (`crop_name`);

--
-- Constraints for dumped tables
--

--
-- Constraints for table `district wise production of crop`
--
ALTER TABLE `district wise production of crop`
  ADD CONSTRAINT `district wise production of crop_ibfk_1` FOREIGN KEY (`Crop name`) REFERENCES `crops` (`crop name`);

--
-- Constraints for table `year wise crop production`
--
ALTER TABLE `year wise crop production`
  ADD CONSTRAINT `year wise crop production_ibfk_1` FOREIGN KEY (`crop_name`) REFERENCES `crops` (`crop name`);
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
